export enum ServiceCallActionType {
  SERVICE_CALL_CREATE_REQUEST = 'SERVICE_CALL_CREATE_REQUEST',
  SERVICE_CALL_CREATE_REQUEST_SUCCESS = 'SERVICE_CALL_CREATE_REQUEST_SUCCESS',
  SERVICE_CALL_CREATE_REQUEST_FAIL = 'SERVICE_CALL_CREATE_REQUEST_FAIL',
  SERVICE_CALL_GET_ALL_REQUEST = 'SERVICE_CALL_GET_ALL_REQUEST',
  SERVICE_CALL_GET_ALL_REQUEST_SUCCESS = 'SERVICE_CALL_GET_ALL_REQUEST_SUCCESS',
  SERVICE_CALL_GET_ALL_REQUEST_FAIL = 'SERVICE_CALL_GET_ALL_REQUEST_FAIL',
  SERVICE_CALL_GET_REQUEST = 'SERVICE_CALL_GET_REQUEST',
  SERVICE_CALL_GET_REQUEST_SUCCESS = 'SERVICE_CALL_GET_REQUEST_SUCCESS',
  SERVICE_CALL_GET_REQUEST_FAIL = 'SERVICE_CALL_GET_REQUEST_FAIL',
}
